name: ea-drought-burn
channels:
- conda-forge
dependencies:
- pip

# General science packages
- imbalanced-learn
- matplotlib
- numpy
- numpy_groupies
- scikit-learn
- seaborn

# Geospatial packages
- contextily
- earthpy
- geopandas
- rioxarray
- xarray

# Jupyter Notebook packages
- jupyterlab
- jupyter_contrib_nbextensions
